language: android
sudo: false

notifications:
  email: false

cache: 
  directories: 
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    - tools
    - platform-tools

    - build-tools-26.0.2
    - android-26

    - build-tools-26.0.0
    - build-tools-25.0.1
    - android-25

    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

licenses: 
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-c81a61d9
    - android-sdk-license-.+
    - google-gdk-license-.+

before_cache: 
  - "rm -f $HOME/.gradle/caches/modules-2/modules-2.lock"

before_install: 
    - "chmod +x gradlew"

before_script:
    - echo "Travis branch is $TRAVIS_BRANCH"

script:
    - "./gradlew clean build test"